# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!
source 'http://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'ContactCard_1' do
pod 'Alamofire', '~> 3.0'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
end

target 'ContactCard_1Tests' do

end

target 'ContactCard_1UITests' do

end

target 'Airplane_2' do

end

target 'Airplane_2Tests' do

end

target 'Airplane_2UITests' do

end

